name: ABMCAFK
main: server.alanbecker.net.Main
version: 1.0
api-version: 1.20
author: MasterGabeMOD
permissions:
  abmc.afk.ignore:
    description: Allows a player to be ignored by the AFK plugin
    default: op