name: ABMCAFK
main: server.alanbecker.net.AFK
version: 1.4
api-version: 1.20
author: MasterGabeMOD
depend: [ProtocolLib]
permissions:
  abmc.afk.ignore:
    description: Allows a player to be ignored by the AFK plugin
    default: op
  abmc.afk.mod:
    description: Allows checking of AFK times of players
    default: op
  abmc.afk.reload:
    description: Allows reloading of the AFK plugin configuration
    default: op
commands:
  afkcheck:
    description: Check how long a player has been AFK or reload the configuration
    usage: /afkcheck <player|reload>
    permission: abmc.afk.mod
